# @package _group_

# Arguments that we want to pass via env into slurm job launcher
env_args:
  project_dir: ${project_release_dir}

num_gpus: 4
print_only: false
use_qos: false

git_hash: {_target_: src.infra.utils.get_git_hash}
experiment_name: ${dataset.name}_${model.name}_${sampling.name}_${exp_suffix}
experiment_name_with_hash: ${experiment_name}-${git_hash}
experiments_dir: experiments
project_release_dir: ${env.base_project_dir}/${experiments_dir}/${experiment_name_with_hash}
job_sequence_length: 1

sbatch_args:
  constraint: "v100"
  time: "1-0"
  gres: gpu:${num_gpus}
  cpus-per-task: 5
  mem:
    _target_: src.infra.utils.num_gpus_to_mem
    num_gpus: ${num_gpus}
    mem_per_gpu: 64
  # mem-per-gpu: 64G
  cpus-per-gpu: 5
  comment: ${experiment_name}

sbatch_args_str:
  _target_: src.infra.utils.cfg_to_args_str
  cfg: ${sbatch_args}

env_args_str:
  _target_: src.infra.utils.cfg_to_args_str
  cfg: ${env_args}
  use_dashes: true
