# @package _group_

python_bin: ${env.base_project_dir}/env/bin/python
before_train_commands: []
torch_extensions_dir: "/tmp/torch_extensions"
objects_to_copy:
  - ${env.base_project_dir}/src
  - ${env.base_project_dir}/configs
# A list of objects that are static and too big
# to be copy-pasted for each experiment
symlinks_to_create:
  - ${env.base_project_dir}/data
tmp_dir: "/tmp"
